import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: {
    default: "Projeto",
    template: "Projeto - %s",
  },
  description: "Generated by create next app",
  openGraph: {
    title: "Projeto",
    description: "Generated by create next app",
    siteName: "Projeto",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
