import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Serviços",
  description: "Generated by create next app",
};

export default function ServicesRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
